drop schema if exists criaturas;

create schema criaturas;
use criaturas;

drop table if exists enemigos;
drop table if exists rasgos;
drop table if exists acciones;
drop table if exists acciones_enemigos;
drop table if exists rasgos_enemigos;

create table enemigos (
	nombre varchar (100),
    imagen varchar (100),
    alineamiento enum (
    'Legal bueno','Neutral bueno','Caótico bueno',
	'Legal neutral','Neutral puro','Caótico neutral',
	'Legal malo','Neutral malo','Caótico malo'
    ),
    tipo varchar (45),
    tamanio varchar(45),
    idiomas varchar(100),
    sentidos varchar(100),
    habilidades varchar(100),
    desafio float,
    clase_armadura tinyint,
    puntos_golpe int,
    fuerza tinyint,
    destreza tinyint,
    constitucion tinyint,
    inteligencia tinyint,
    sabiduria tinyint,
    carisma tinyint,
    
    constraint pk_enemigos primary key(nombre)
);


create table rasgos (
	nombre varchar(100),
    descripcion varchar(250),
    
    constraint pk_rasgos primary key(nombre)
);

create table acciones (
	nombre varchar(100),
    descripcion varchar(300),
    
    constraint pk_acciones primary key(nombre)
);

create table acciones_enemigos(
	nombre_accion varchar(100),
    nombre_enemigo varchar(100),
    
    constraint pk_acciones_enemigos primary key(nombre_accion,nombre_enemigo),
    constraint fk_nombre_accion_AE foreign key (nombre_accion) references acciones(nombre),
    constraint fk_nombre_enemigo_AE foreign key (nombre_enemigo) references enemigos(nombre)
);

create table rasgos_enemigos(
	nombre_rasgo varchar(100),
    nombre_enemigo varchar(100),
    
    constraint pk_rasgos_enemigos primary key(nombre_rasgo,nombre_enemigo),
    constraint fk_nombre_rasgo_RE foreign key (nombre_rasgo) references rasgos(nombre),
    constraint fk_nombre_enemigo_RE foreign key (nombre_enemigo) references enemigos(nombre)
);


insert into enemigos 
(nombre,imagen,alineamiento,tipo,tamanio,idiomas,sentidos,habilidades,desafio,clase_armadura,puntos_golpe,fuerza,destreza,constitucion,inteligencia,sabiduria,carisma)
values
/*LETRA A*/ 
('Planetar','img/planetar.png','Legal bueno','Celestial','Grande','Todos','Vision Verdadera, Percepcion Pasiva 21','Percepcion +11',16,19,200,24,20,24,19,22,25),
('Aparicion','img/aparicion.png','Neutral malo','Muerto viviente', 'Mediano','Comun','Vision en la Oscuridad, Percepcion Pasiva 12','',5,13,67,6,16,16,12,14,15),
('Azotamentes','img/azotamentes.png','Legal malo','Aberración','Mediano','Infracomun, Profundidades, Telepatia','Vision en la Oscuridad, Percepcion Pasiva 16','C.Arcano +7, Engaño +6, Perspicacia +6',7,15,71,11,12,12,19,17,17),
/*LETRA B*/
('Behir','img/behir.png','Neutral malo','Monstruosidad','Enorme','Draconido','Vision en la Oscuridad, Percepcion Pasiva 16','Percepcion +6, Sigilo +7',11,17,168,23,16,18,7,14,12),
('Bestia de Trémula','img/tremula.png','Legal malo','Monstruosidad','Grande','','Vision en la Oscuridad, Percepcion Pasiva 11','',3,13,85,18,15,16,6,12,8),
('Broza movediza','img/broza.png','Neutral puro','Planta','Grande','','Vision Ciega, Percepcion Pasiva 10','Sigilo +2',5,15,136,18,8,16,5,10,5),
/*LETRA C*/
('Cocatriz','img/cocatriz.png','Neutral puro','Monstruosidad','Pequeño','','Vision en la Oscuridad, Percepcion Pasiva 11','',0.5,11,27,6,12,12,2,13,5),
('Cambion','img/cambion.png','Legal malo','Infernal','Mediano','Abisal, Comun, Infernal','Vision en la Oscuridad, Percepcion Pasiva 14','Engaño +6, Intimidacion +6, Percepcion +4',5,19,82,18,18,16,14,12,16),
('Caballero de la Muerte','img/caballeroMuerte.png','Caótico malo','Muerto viviente','Mediano','Abisal, Comun','Vision en la Oscuridad, Percepcion Pasiva 13','',17,20,180,20,11,20,12,16,18),
('Contemplador','img/beholder.png','Legal Malo','Aberración','Grande','Infracomun, Profundidades','Vision en la Oscuridad, Percepcion Pasiva 22','Percepcion +12',13,18,180,10,14,18,17,15,17),
/*LETRA D*/
('Dríade','img/driade.png','Neutral puro','Feérico','Mediano','Elfo, Silvano','Vision en la Oscuridad, Percepcion Pasiva 14','Percepcion +4, Sigilo +5',1,11,22,10,12,11,14,15,18),
('Hezrou','img/hezrou.png','Caótico malo','Infernal','Grande','Abisal, Telepatia','Vision en la Oscuridad, Percepcion Pasiva 11','',8,16,136,19,17,20,5,12,13),
('Anjanath','img/anjanath.png','Neutral puro','Bestia','Enorme','','Percepcion Pasiva 14','Percepcion +4',8,13,136,25,10,19,2,12,9),
/*LETRA E*/
('Elemental de aire','img/elementalAire.png','Neutral puro','Elemental','Grande','Aurano','Vision en la Oscuridad, Percepcion Pasiva 10','',5,15,90,14,20,14,6,10,6),
('Estirge','img/estirge.png','Neutral puro','Bestia','Diminuto','','Vision en la Oscuridad, Percepcion Pasiva 9','',0.12,14,2,4,16,11,12,8,6),
('Espectro','img/espectro.png','Caótico malo','Muerto viviente','Mediano','','Vision en la Oscuridad, Percepcion Pasiva 10','',1,12,22,1,14,11,10,10,11),
/*LETRA F*/
('Flumph','img/flumph.png','Legal bueno','Aberración','Pequeño','Telepatia','Vision en la Oscuridad, Percepcion Pasiva 12','C.Arcano +4, Historia +4, Religion +4',0.12,12,7,6,15,10,14,14,11),
('Fomoré','img/fomore.png','Caótico malo','Gigante','Enorme','Gigante, Infracomun','Vision en la Oscuridad, Percepcion Pasiva 18','Percepcion +8, Sigilo +3',8,14,149,23,10,20,9,14,6),
('Fuego fatuo','img/fuegoFauto.png','Caótico malo','Muerto viviente','Diminuto','','Vision en la Oscuridad, Percepcion Pasiva 12','',2,19,22,1,28,10,13,14,11),
/*LETRA G*/
('Garra reptante','img/garraReptante.png','Neutral malo','Muerto viviente','Diminuto','','Vision Ciega, Percepcion Pasiva 10','',0,12,2,13,14,11,5,10,4),
('Gigante de Piedra','img/gigantePiedra.png','Neutral puro','Gigante','Enorme','Gigante','Vision en la Oscuridad, Percepcion Pasiva 14','Atletismo +12, Percepcion +4',7,17,126,23,15,20,10,12,9),
('Guardian Escudo','img/guardianEscudo.png','Neutral puro','Automata','Grande','','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 10','',7,17,142,18,8,18,7,10,3),
/*LETRA H*/
('Horror Ganchudo','img/ganchudo.png','Neutral puro','Monstruosidad','Grande','Horror Ganchudo','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 13','Percepcion +3',3,15,75,18,10,15,6,12,7),
('Horror Acorazado','img/horrorAcorazado.png','Neutral puro','Automata','Mediano','','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 14 ','Percepcion +4',4,20,60,18,13,16,10,10,10),
('Hidra','img/hidra.png','Neutral puro','Monstruosidad','Enorme','','Vision en la Oscuridad, Percepcion Pasiva 16','Percepcion +6',8,15,172,20,12,20,2,10,7),
/*LETRA K*/
('Kraken','img/kraken.png','Caótico malo','Monstruosidad','Gargantua','','Vision Verdadera, Percepcion Pasiva 14','',23,18,472,30,11,25,22,18,20),
('Kobold','img/kobold.png','Legal malo','Humanoide','Pequeño','Comun, Draconido','Vision en la Oscuridad, Percepcion Pasiva 8','',0.12,12,5,7,15,9,8,7,8),
('Kuo-Toa','img/kuotoa.png','Neutral malo','Humanoide','Mediano','Infracomun','Vision en la Oscuridad, Percepcion Pasiva 14','Percepcion +4',0.25,13,18,13,10,11,11,10,8),
/*LETRA L*/
('Liche','img/liche.png','Caótico malo','Muerto viviente','Mediano','Comun, Elfo, Enano, Druidico, Abisal, Celestial','Vision Verdadera, Percepcion Pasiva 19','C.Arcano +18, Historia +12, Perspicacia +9',21,17,135,11,16,16,20,14,16),
('Hombre Rata','img/hombreRata.png','Legal Malo','Humanoide','Mediano','Comun','Vision en la Oscuridad, Percepcion Pasiva 12','Percepcion +2, Sigilo +4',2,12,33,10,15,12,11,10,8),
('Lamia','img/lamia.png','Caótico malo','Monstruosidad','Grande','Abisal, Comun','Vision en la Oscuridad, Percepcion Pasiva 12','Engaño +7, Perspicacia +4, Sigilo +3',4,13,97,16,13,15,14,15,16),
/*LETRA M*/
('Mantoscuro','img/mantoscuro.png','Neutral puro','Monstruosidad','Pequeño','','Vision Ciega, Percepcion Pasiva 10','Sigilo +3',0.5,11,22,16,12,13,2,10,5),
('Mephit de polvo','img/mephit.png','Neutral malo','Elemental','Pequeño','Aurano, Terrano','Vision en la Oscuridad, Percepcion Pasiva 12','Percepcion +2, Sigilo +4',0.5,12,17,5,14,10,9,11,10),
('Mimico','img/mimico.png','Neutral puro','Monstruosidad','Mediano','','Vision en la Oscuridad, Percepcion Pasiva 11','Sigilo +5',2,12,58,17,12,15,5,13,8),
/*LETRA N*/
('Naga Guardiana','img/naga.png','Legal bueno','Monstruosidad','Grande','Celestial, Comun','Vision en la Oscuridad, Percepcion Pasiva 14','',10,18,127,19,18,16,16,19,18),
('Nótico','img/notico.png','Neutral malo','Aberración','Mediano','Infracomun','Vision Verdadera, Percepcion Pasiva 12','C.Arcano +3, Percepcion +2, Perspicacia +4',2,15,45,14,16,16,13,10,8),
/*LETRA O*/
('Osgo','img/osgo.png','Caótico malo','Humanoide','Mediano','Comun, Goblin','Vision en la Oscuridad, Percepcion Pasiva 10','Sigilo +6, Supervivencia +2',1,16,27,15,14,13,8,11,9),
('Oni','img/oni.png','Legal malo','Gigante','Grande','Comun, Gigante','Vision en la Oscuridad, Percepcion Pasiva 14','C.Arcano +5, Engaño +8, Percepcion +4',7,16,110,19,11,16,14,12,15),
('Oso Lechuza','img/osoLechuza.png','Neutral puro','Monstruosidad','Grande','','Vision en la Oscuridad, Percepcion Pasiva 13','Percepcion +3',3,13,59,20,12,17,3,12,7),
/*LETRA P*/
('Pixie','img/pixie.png','Neutral bueno','Feérico','Diminuto','Silvano','Percepcion Pasiva 14','Percepcion +4, Sigilo +7',0.25,15,1,2,20,8,10,14,15),
('Pesadilla','img/pesadilla.png','Neutral malo','Infernal','Mediano','','Percepcion Pasiva 11','',3,13,68,18,15,16,10,13,15),
('Perforador','img/perforador.png','Neutral puro', 'Mosntruosidad','Mediano','','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 8','Sigilo +5',0.5,15,22,10,13,16,1,7,3),
/*LETRA Q*/
('Quaggoth','img/quaggoth.png','Caótico neutral','Humanoide','Mediano','Infracomun','Vision en la Oscuridad, Percepcion Pasiva 11','Atletismo +5',2,13,45,17,12,16,6,12,7),
('Quimera','img/quimera.png','Caótico malo','Monstruosidad', 'Grande','','Vision en la Oscuridad, Percepcion Pasiva 18','Percepcion +8',6,14,114,19,11,19,3,14,10),
/*LETRA R*/
('Rakshasa','img/rakhasa.png','Legal malo','Infernal','Mediano','Comun, Infernal','Vision en la Oscuridad, Percepcion Pasiva 13','Engaño +10, Perspicacia +8',13,16,110,14,17,18,13,16,20),
('Remorhaz','img/remorhaz.png','Neutral puro','Monstruosidad','Enorme','','Vision en la Oscuridad, Sentir Vibraciones, Percepcion Pasiva 10','',11,17,195,24,13,21,4,10,5),
('Roc','img/roc.png','Neutral puro','Monstruosidad','Gargantua','','Percepcion Pasiva 14','Percepcion +4',11,15,248,28,10,20,3,10,9),
/*LETRA S*/
('Súcubo','img/sucubo.png','Neutral malo','Infernal','Mediano','Abisal, Comun, Infernal, Telepatia','Vision en la Oscuridad, Percepcion Pasiva 15','Engaño +9, Persuasion +9, Sigilo +7',4,15,66,8,17,13,15,12,20),
('Saga de la Noche','img/saga.png','Neutral malo','Infernal','Mediano','Abisal, Comun, Infernal, Primordial','Vision en la Oscuridad, Percepcion Pasiva 16','Engaño +7, Percepcion +6, Perspicacia +6',5,17,112,18,15,16,16,14,16),
('Semidragon Rojo Veterano','img/semidragonRV.png','Neutral puro','Humanoide','Mediano','Comun, Draconido','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 12','Atletismo +5, Percepcion +2',5,18,65,16,13,14,10,11,10),
/*LETRA T*/
('Thri-kreen','img/thrikreen.png','Caótico neutral','Humanoide','Mediano','Thri-kreen','Vision en la Oscuridad, Percepcion Pasiva 13','Percepcion +3, Sigilo +4, Supervivencia +3',1,15,33,12,15,13,8,12,7),
('Tarasca','img/tarasca.png','Neutral puro','Monstruosidad','Gargantua','','Vision Ciega, Percepcion Pasiva 10','',30,25,676,30,11,30,3,11,11),
('Troglodita','img/troglodita.png','Caótico malo','Humanoide', 'Mediano','Troglodita','Vision en la Oscuridad, Percepcion Pasiva 10','Sigilo +2',0.25,11,13,14,10,14,6,10,6),
/*LETRA U*/
('Unicornio','img/unicornio.png','Legal bueno','Celestial','Grande','Celestia, Elfo, Silvano, Telepatia','Vision en la Oscuridad, Percepcion Pasiva 13','',5,12,67,18,14,15,11,17,16),
/*LETRA V*/
('Vampiro','img/vampiro.png','Legal malo','Muerto viviente','Mediano','Comun','Vision en la Oscuridad, Percepcion Pasiva 17','Percepcion +7, Sigilo +9',13,16,144,18,18,18,17,15,18),
('Engendro Vampírico','img/engendroV.png','Neutral malo','Muerto viviente','Mediano','Comun','Vision en la Oscuridad, Percepcion Pasiva 13','Percepcion +3, Sigilo +6',5,15,82,16,16,16,11,10,12),
/*LETRA X*/
('Xorn','img/xorn.png','Neutral puro','Elemental','Mediano','Terrano','Vision en la Oscuridad, Sentir Vibraciones, Percepcion Pasiva 16','Percepcion +6, Sigilo +3',5,19,73,17,10,22,11,10,11),
/*LETRA Y*/
('Yeti abominable','img/yeti.png','Caótico malo','Monstruosidad','Enorme','Yeti','Vision en la Oscuridad, Percepcion Pasiva 15','Percepcion +5, Sigilo +4',9,15,137,24,10,22,9,13,9),
('Yuan-ti Purasangre','img/yuanti.png','Neutral malo','Humanoide','Mediano','Abisal, Comun, Draconido','Vision en la Oscuridad, Percepcion Pasiva 13','Engaño +6, Percepcion +3, Sigilo +3',1,11,40,11,12,11,13,12,14),
('Mezzoloth','img/mezzoloth.png','Neutral malo','Infernal','Mediano','Abisal, Infernal, Telepatia','Vision Ciega, Vision en la Oscuridad, Percepcion Pasiva 13','Percepcion +3',5,18,75,18,11,16,7,10,11),
/*LETRA Z*/
('Zombi','img/zombi.png','Neutral malo','Muerto viviente','Mediano','','Vision en la Oscuridad, Percepcion Pasiva 8','',0.25,8,22,13,6,16,3,6,5)
;
/*---------RASGOS---------*/
insert into rasgos (nombre,descripcion) values
('Resistencia a Contundente','Recibe la mitad de daño de este tipo'),
('Resistencia a Cortante','Recibe la mitad de daño de este tipo'),
('Resistencia a Perforante','Recibe la mitad de daño de este tipo'),
('Resistencia a Ácido','Recibe la mitad de daño de este tipo'),
('Resistencia a Frío','Recibe la mitad de daño de este tipo'),
('Resistencia a Fuego','Recibe la mitad de daño de este tipo'),
('Resistencia a Relámpago','Recibe la mitad de daño de este tipo'),
('Resistencia a Trueno','Recibe la mitad de daño de este tipo'),
('Resistencia a Radiante/Sagrado','Recibe la mitad de daño de este tipo'),
('Resistencia a Necrótico','Recibe la mitad de daño de este tipo'),
('Resistencia a Veneno','Recibe la mitad de daño de este tipo'),
('Inmunidad a Contundente','No recibe daño de este tipo'),
('Inmunidad a Cortante','No recibe daño de este tipo'),
('Inmunidad a Perforante','No recibe daño de este tipo'),
('Inmunidad a Ácido','No recibe daño de este tipo'),
('Inmunidad a Frío','No recibe daño de este tipo'),
('Inmunidad a Fuego','No recibe daño de este tipo'),
('Inmunidad a Relámpago','No recibe daño de este tipo'),
('Inmunidad a Trueno','No recibe daño de este tipo'),
('Inmunidad a Radiante/Sagrado','No recibe daño de este tipo'),
('Inmunidad a Necrótico','No recibe daño de este tipo'),
('Inmunidad a Veneno','No recibe daño de este tipo'),
('Absorción de Ácido','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Frío','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Fuego','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Relámpago','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Trueno','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Radiante/Sagrado','No recibe daño de este tipo, en su lugar recupera vida'),
('Absorción de Necrótico','No recibe daño de este tipo, en su lugar recupera vida'),
('Vulnerabilidad a Ácido','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Frío','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Fuego','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Psíquico','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Relámpago','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Trueno','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Radiante/Sagrado','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Necrótico','Recibe el doble de daño de este tipo'),
('Vulnerabilidad a Veneno','Recibe el doble de daño de este tipo'),
('Inmunidad a Asustado','No puede ser afectado por el estado alterado'),
('Inmunidad a Cansancio','No puede ser afectado por el estado alterado'),
('Inmunidad a Hechizado','No puede ser afectado por el estado alterado'),
('Inmunidad a Agarrado','No puede ser afectado por el estado alterado'),
('Inmunidad a Apresado','No puede ser afectado por el estado alterado'),
('Inmunidad a Derribado','No puede ser afectado por el estado alterado'),
('Inmunidad a Envenenado','No puede ser afectado por el estado alterado'),
('Inmunidad a Paralizado','No puede ser afectado por el estado alterado'),
('Inmunidad a Aturdido','No puede ser afectado por el estado alterado'),
('Inmunidad a Inconsciente','No puede ser afectado por el estado alterado'),
('Inmunidad a Petrificado','No puede ser afectado por el estado alterado'),
('Inmunidad a Cegado','No puede ser afectado por el estado alterado'),
('Inmunidad a Ensordecido','No puede ser afectado por el estado alterado'),
('Armas Angelicales','Las armas inflingen daño Mágico, adicionalmente producen 5d8 de daño adicional'),
('Percepcion Divina','Reconoce cualquier mentira que escuche'),
('Lanzamiento de Conjuros Innato','Tiene la capacidad de lanzar conjuros'),
('Resistencia Mágica','Tiene ventaja contra Tiradas de Salvacion para evitar conjuros'),
('Movimiento Incorpóreo','Puede moverse a través de otras criaturas y objetos, pero solo la mitad de su velocidad'),
('Velocidad a pie 1','30'),
('Velocidad a pie 2','60'),
('Velocidad a vuelo 1','30'),
('Velocidad a vuelo 2','60'),
('Velocidad a nado 1','30'),
('Velocidad a nado 2','60'),
('Velocidad al trepar 1','30'),
('Velocidad al trepar 2','60'),
('Evitar','Recibe la mitad de daño al fallar una Tirada de Salcavión y ningún daño si la pasa'),
('Desplazamiento','Proyecta una ilusión haciendo que las tiradas de ataque en su contra tengan desventaja, si recibe daño de esta forma este rasgo dejará de funcionar hasta el siguiente turno'),
('Comandar Muertos Vivientes','Cualquier Muerto Viviente a 60 pies tiene ventaja contra tiradas de Salvacion contra efectos de Expulsar Muertos Vivientes'),
('Bendición Infernal','La CA incluye el Bonus por Carisma'),
('Cono Antimagia','Hallá donde se mire el cono de su visón no permitira el uso de hechizos, propios y enemigos'),
('Hedor','Cualquier criatura a 10 pies deberá lanzar una tirada de Salvacion contra Constitucion o se envenenará'),
('Hablar con Bestias y Plantas','Poder de comunicación con las bestias y plantas como si hablarán en idioma comun'),
('Paso Arbóreo','Puede entrar en un arbol vivo a 10 pies de ella y salir por otro a 60 pies.'),
('Forma de Aire','Puede ocupar el mismo espacio que otra criatura, ademas podrá pàsar por espacios de 1 sola pulgada'),
('Sensibilidad a la luz Solar','Desventaja en tiradas de Salvacion y de ataque que dependan de la vista bajo la luz del sol'),
('Telepatía Avanzada','Puede leer conversaciones telepatia a 60 pies y no puede ser sorprendido por ello'),
('Vulnerable a ser Derribado','Si es derribado tira un dado, si es impar caera con la cabeza yq uedara incapacitado, deberá superar una Tirada de Salvacion de destreza 10 para incorporarse'),
('Velo Telepático','Su mente no puede ser leida de ninguna forma'),
('Devorar Vida','Se elige una criatura con 0 puntos de golpe pero que aun este viva, lanzará una Tirada de Salvación de Constitución 10, si la falla la criatura muere y el poseedor de este rasgo se cura 3d6'),
('Efímero','No puede vestir o llevar nada'),
('Iluminación Variable','Emites una luz brillante de 5 a 20 pies'),
('Inmunidad a Expulsion','Inmunidad contra los efectos que expulsan a Muertos Vivientes'),
('Camuflaje con la Piedra','Ventaja en Sigilo para esconderse en terrenos rocosos'),
('Vínculo','Se esta vinculado a un amuleto, se puede usar este amuleto para llamar al vinculado telepaticamente. Si ambos estan a menos de 60 pies el Vinculado recibe la mitad de daño que iba a recibir el portador'),
('Regeneración','Regenera 10 Puntos de Golpe al comienzo de su turno'),
('Aguantar la Respiración','Aguanta la respiración por una hora'),
('Múltiples Cabezas','Mientras haya una cabeza tiene ventaja contra asustado, aturdido, cegado, ensordecido, hechizado e incosnciente. Si se corta una cabeza creceran 2 de esta y se curará 10 por cada cabeza nueva, a no ser que haya recibido daño de fuego'),
('Cabezas Reactivas','Obtienes una reaccion por cada cabeza'),
('Vigilante','Aun durmiendo, una de las cabezas se mantendra despierta'),
('Ecolocalización','Si queda ensordecido perderá la Vision Ciega'),
('Oído Agudo','Ventaja en las tiradas que dependan del oído'),
('Ataque en Manada','Ventaja en tiradas de ataque si hay otro aliado cerca'),
('Anfibio','Puede respirar dentro y fuera del agua'),
('Libertad de Movimiento','Ignora los terrenos, su velocidad no puede ser modificada'),
('Monstruo de Asedio','Doble de daño a estructuras y objetos'),
('Percepción Sobrenatural','Detecta cualquier criatura invisible o en el plano etereo a 30 pies de distancia o menos'),
('Escurridizo','Ventaja para escapar de un agarre'),
('Olfato Agudo','Ventaja en tiradas que dependan del olfato'),
('Cambiaformas','Puede elegir cambiar de forma a su antojo, si muere volverá a su forma original'),
('Resistencia Legendaria','Puedes elegir tener exito en una tirada de Salvacion que hayas fallado, 3 veces por dia'),
('Rejuvenecimiento','Si se posee una Filacterria y es destruida, obtendras un nuevo cuerpo en 1d10 Dias, estando este nuevo cuerpo en plenitud de tus facultades'),
('Apariencia Falsa','Mientras te mantengas quieto seras indistinguible del fondo'),
('Explotar al Morir - Polvo','Una nube de polvo aparecera y obligara a las criaturas a 5 pies o menos a pasar una Tirada de Salvacion de Constitucion 10 o quedarán cegados por 1 minuto'),
('Apresador','Ventaja en tiradas de ataque contra cualquier criatura que tenga agarrada'),
('Adhesivo','Se adhiere a cualquiera que lo toque, si la criatura es Enorme o mas pequeña quedarán apresadas'),
('Vista Aguda','Ventaja en tiradas que dependan de la vista'),
('Armas Mágicas','Los ataques se consideran mágicos'),
('Bruto','Las armas cuerpo a cuerpo inflingen un Dado adicional de su daño'),
('Ataque por Sorpresa','Si se soprende a una criatura se inflinge un Dado adicional del daño del arma'),
('Trepar cual Arácnido','Puedes trepar por superficies dificiles, incluyendo boca abajo'),
('Otorgar Resistencia al Fuego','Puede otorgar Resistencia a Fuego a un aliado'),
('Furia','Ventaja en tiradas de ataque si le quedan menos de un 10% de sus Puntos de Golpe, ademas infligira un dado de daño adicional con las armas'),
('Inmunidad Mágica Limitada','No pueder ser afectado o detectado por Conjuros de nivel 6 o menos'),
('Cuerpo Abrasador','Cualquier criatura que entre en contacto contigo recibirá 3d6 de daño de fuego'),
('Enlace Telepático','Ignoras las restricciones de la Telepátia cuando la usas para comunicarte con alguien hechizado por ti'),
('Caparazón Reflectante','Si eres objetivo de un conjuro cuya area sea una linea o un proyectil mágico tira un d6, de 1 a 5 no te afecta, con 6 ademas devolveras el daño contra su lanzador'),
('Caparazón Camaleónico','Puedes cambiar el color de tu piel (caparazon) para imitar el entorno y obtienes ventaja en tiradas de Sigilo para esconderte'),
('Saltar sin Carrera','Puedes saltar longitudinalmente 30 pies o verticalmente 15 pies'),
('Cargar','Si te mueves al nenos 20 pies en linea recta hacia un objetivo y despues entra un ataque contra el, el objetivo recibe 2d8 de daño adicional'),
('Escape Brumoso','Cuando tu vida llege a 0, en vez de caer te convertiras en una nube de polvo, buscando tu lugar de descanso en menos de 2 horas o moriras'),
('Prohibición Vampírica','No puedes entrar en una vivienda si que te inviten a entrar'),
('Dañado por el Agua Corriente','Recibirás 20 puntos de daño de Ácido si terminas el turno den agua corriente'),
('Estaca en el Corazón','Si se recibe una estaca de madera en el corazon mientras estas en tu lugar de descanso quedaras paralizado hasta extraerla'),
('Hipersensibilidad a la Luz Solar','Recibiras 20 puntos de daño radiante si empiezas el turno bajo la luz del Sol y tendras desventaja en cualquier tipo de tirada'),
('Deslizarse por la Tierra','Puedes excavar a través de la tierra o piedra que no sean mágicas, sin modificar el material por el que te desplazas'),
('Miedo al Fuego','Si recibes daño de Fuego tendrás desventaja en las tiradas de ataque y Salvacion hasta el final de tu turno'),
('Camuflarse en la Nieve','Ventaja en tiradas de Sigilo para esconderse en terrenos cubiertos de nieve'),
('Fortaleza de Muerto Viviente','Siempre que tus puntos vaya a ser reducidos a 0 debes hacer una Tirada de Salvacion de Constitucion 5 más el daño sufrido, si la pasas tendras 1 punto de vida. Este efecto se anula si recibes daño Radiante')
;
/*---------ACCIONES---------*/
insert into acciones (nombre,descripcion) values
('Ataque múltiple 1','Se realiza 2 acciones de atacar'),
('Ataque múltiple 2','Se realiza 3 acciones de atacar'),
('Espadón','Ataque cuerpo a cuerpo, +12 a impactar, 4d6+7 de daño cortante y 5d8 radiante'),
('Toque Sanador','Tocas a otra criatura y esta recupera 6d8+3 puntos de golpe y queda liberada de cualquier maldición, enfermedad, veneno, ceguera o sordera'),
('Consumir Vida','Ataque cuerpo a cuerpo, +6 a impactar, 4d8+3 de daño necrotico. Tirada de Salvación de Constitucion 14 o sus puntos de golpe Máximos tambien se verán reducidos'),
('Crear Espectro','Eliges un humanoide recientemente muerto, el objetivo se alza como un espectro a tus ordenes'),
('Tentáculos 2','Ataque cuerpo a cuerpo, +7 a impactar, 2d10+4 de daño psíquico. Si el objetivo es mediano o menor, Tirada de Salvación de fuerza 15 para escapar y una de inteligencia 15 para no estar aturdido'),
('Extraer cerebro',' Ataque cuerpo a cuerpo, +7 al impactar, solo a un objetivo agarrado. 10d10 de daño perforante, si este daño reduce sus puntos de golpe a 0, te alimentaras de su cerebor y morirá'),
('Descarga mental','Ataque a distancia en area, cono de 60 pies desde el lanzador. Tirada de Salvación de inteligencia 15 o 4d8+4 de daño psíquico y aturdido durante 1 minuto'),
('Mordisco 2','Ataque cuerpo a cuerpo, +10 a impactar, 3d10+6 de daño perforante'),
('Mordisco 3','Ataque cuerpo a cuerpo, +10 a impactar, 6d10+7 de daño perforante'),
('Constreñir','Ataque cuerpo a cuerpo, +10 a impactar, criatura Grande o menor. 2d10+6 de daño contundente y 2d10+6 cortante. Tirada de Salvacion de fuerza 16 para escapar del agarre'),
('Aliento de Relámpago','Ataque a distancia en area, linea de 20x5 pies. Tirada de Salvación de Destreza 16 o 12d10 de daño de relámpago, mitad si superan la Tirada de Salvación '),
('Engullir',' Ataque cuerpo a cuerpo, +10 a impactar, sobre criatura mediana o menor. Al impactar engullira al objetivo, desde dentro tendra que hacer más de 30 puntos de daño en un turno para poder salir, o recibirá 6d6 de daño de ácido por turno'),
('Tentáculos 1','Ataque cuerpo a cuerpo, +6 a impactar,1d6+4 de daño contundente y 1d6 perforante'),
('Golpe 2','Ataque cuerpo a cuerpo, +7 a impactar, 2d8+4 de daño contundente'),
('Absorber','Ataque cuerpo a cuerpo,sobre una criatura Mediana o más pequeña a la que tenga agarrada. El objetivo está apresado, cegado y no puede respirar, Tirada de Salvación de Constitución 14 al principio de cada uno de los turnos o recibirá 2d8 + 4 de daño contundente'),
('Espada Larga','Ataque cuerpo a cuerpo,+11 a impactar,1d8 + 5 de daño cortante y 4d8 necrótico'),
('Orbe de Fuego Infernal','Ataque a distancia en area, esfera de 20 pìes, hasta 120 pies de distancia. Tirada de Salvacion de Destreza 18, 10d6 de daño de fuego y 10d6 necrótico al fallar, mitad de daño al pasar la tirada'),
('Lanza','Ataque con arma cuerpo a cuerpo o a distancia, +7 a impactar,1d6+4 de daño perforante y 1d6 de fuego'),
('Rayo de fuego','Ataque a distancia, +7 a impactar, 120 pies, 3d6 de daño de fuego'),
('Encanto Infernal','Humanoide elegido, Tirada de Salvacion de Sabiduria 14 o quedará hechizado durante 1 día'),
('Mordisco Petrificante','Ataque cuerpo a cuerpo, +3 a impactar, 1d4+1 de daño perforante, Tirada de Salvación de Constitución 11 o quedará petrificado durasnte 24h'),
('Mordisco 1','Ataque cuerpo a cuerpo, +5 a impactar, 4d6 de daño perforante'),
('Rayo Ocular Cautivador','Tirada de Salvación de Sabiduria 16 o quedará hechizado durante 1h'),
('Rayo Ocular Paralizador','Tirada de Salvación de Constitución 16 o quedará paralizado durante 1 min'),
('Rayo Ocular Aterrador','Tirada de Salvación de Sabiduria 16 o quedará asustado durante 1 min, intentando alejarse del enemigo cada turno'),
('Rayo Ocular Ralentizador','Tirada de Salvacion de Destreza 16 o reducira su velocidad a la mitad y solo podrá hacer 1 accion o 1 reaccion en su turno'),
('Rayo Ocular Debilitador','Tirada de Salvación de Constitución 16, 8d8 de daño necrótico si falla y mitad si pasa la tirada'),
('Rayo Ocular Telequinético','Tirada de Salvación de Fuerza 16 o sera apresado y empujado hasta 30 pies'),
('Rayo Ocular Petrificador','Tirada de Salvación de Destreza 16 o empezará a convertirse en piedra y repetirá la tirada en su proximo turno, si falla se convertira en piedra mágicamente hasta que sea curada'),
('Rayo Ocular Somnifero','Tirada de Salvación de Sabiduria o se dormirá durante 1 min'),
('Rayo Ocular Desintegrador','Tirada de Salvación de Destreza 16 o sufrirá 10d8 de daño de fuerza. Si los puntos de golpe llegan a 0 se convertirá en polvo'),
('Rayo Ocular Mortal','Tirada de Salvación de destreza 16 o 10d10 de daño necrótico'),
('Garra 2','Ataque cuerpo a cuerpo, +7 a impactar, 2d6+4 de daño cortante'),
('Cola 1','Ataque cuerpo a cuerpo, +10 a impactar, 3d8+7 de daño contundente'),
('Garrote','Ataque cuerpo a cuerpo, +2 a impactar,1d4 de daño contundente'),
('Encanto Feérico','Humanoide objetivo, Tirada de Salvación de Sabiduria 14 o quedará hechizado, tomará en gran consideración las sugerencias del hechizador'),
('Torbellino','Criaturas cercanas, Tirada de Salvación de Fuerza 13 o 3d8+2 de daño contundente y lanzado hacia arriba 20 pies'),
('Chupar Sangre','Ataque cuerpo a cuerpo, +5 a impactar, 1d4+3 daño perforante y curara al atacante el daño'),
('Zarcillos','Ataque cuerpo a cuerpo,+4 a impactar, 1d4+2 de daño perforante y 1d4 de ácido, Tirada de Salvación de Constitución 10 1d4 de daño de ácido adicional'),
('Rociada Apestosa','Ataque a distancia en area, cono de 15 pies, Tirada de Salvación de Destreza 10, emitiran un olor nauseabundo durante 1d4 horas y estarán envenenados'),
('Garrote Grande','Ataque cuerpo a cuerpo, +9 a impactar, 3d8+6 de daño contundente'),
('Mal de Ojo','Criatura objetivo, Tirada de Salvación de Carisma 14 o 6d8 de daño, mitad si la pasa'),
('Maldición Mal de Ojo','Criatura objetivo, Tirada de Salvación de Carisma 14 o 6d8 de daño, mitad si la pasa. Ademas desventaja en cualquier tirada de Fuerza o Destreza'),
('Descarga','Ataque cuerpo a cuerpo, +4 a impactar, 2d8 de daño relámpago'),
('Invisibilidad','Te vulves invisible hasta que realices otra accion que no sea de movimiento'),
('Garra 1','Ataque cuerpo a cuerpo, +3 a impactar, 1d4+1 de daño cortante'),
('Piedra','Ataque a distancia, +9 a impactar, 4d10+6 de daño contundente, Tirada de Salvación de Fuerza 17 o derribado '),
('Puñetazo','Ataque cuerpo a cuerpo, +7 a impactar, 2d6+4 de daño contundente'),
('Garfio','Ataque cuerpo a cuerpo, +6 a impactar, 2d6+4 de daño perforante'),
('Daga','Ataque cuerpo a cuerpo, +4 a impactar, 1d4+2 de daño perforante'),
('Honda','Ataque a distancia, +4 a impactar, 14d+2 de daño contundente'),
('Tentáculos 3','Ataque cuerpo a cuerpo, +17 a impactar, 3d6 de daño contundente, Tirada de Salvación de Fuerza 18 o apresado'),
('Tormenta de Relámpagos','120 pies alrededor del lanzador, Tirada de Salvación de Destreza 23 o 4d10 de daño relámpago, mitad si pasa.'),
('Red','Ataque a distancia, +3 a impactar, el objetivo queda apresado, Tirada de Salvación de Fuerza 10 para liberarse'),
('Garras',' Ataque cuerpo a cuerpo, +5 a impactar, 2d10+3 de daño cortante'),
('Toque Embriagador','Conjuro cuerpo a cuerpo, +5 a impactar, maldito durante 1 hor, desventaja en todas las tiradas de Sabiduria'),
('Espada Corta','Ataque cuerpo a cuerpo, +4 a impactar, 1d6+2 de daño perforante'),
('Ballesta de Mano','Ataque a distancia, +4 a impactar, 1d6+2 de daño perforante'),
('Toque Paralizante','Conjuro cuerpo a cuerpo, +12 a impactar, 3d6 de daño de frío, Tirada de Salvación de Constitución 18 o paralizado durante 1 min'),
('Mirada Aterradora','Criatura objetivo, Tirada de Salvación de Sabiduria 18 o asustado durante 1 min'),
('Perturbar Vida','Toda criatura viva a 20 pies, Tirada de Salvación Constitucion 18, 6d6 de daño necrotico o mitad si pasan'),
('Lanzar un Truco','Lanza un truco del repertorio de trucos de la clase asociada'),
('Lanzar un Conjuro','Lanza un conjuro del repertorio de conjuros de la clase asociada'),
('Aplastar','Ataque cuerpo a cuerpo, +5 a impactar, 1d6+3 de daño perforante, si es mediano o menor, quedará cegada'),
('Aura de Oscuridad','15 pies al rededor del lanzador y se mueve on el, 10 min de duración, se considera Oscuridad Mágica de nivel 2'),
('Aliento Cegador','Ataque a distancia en area, cono 15 pies, Tirada de Salvación de Destreza 10 o cegado durante 1 min'),
('Pseudópodo','Ataque cuerpo a cuerpo, +5 a impactar, 1d8+3 de daño contundente'),
('Escupir Veneno','Ataque a distancia, +8 a impactar, Tirada de Salvación de Constitución 15 o 10d8 de veneno, mitas si supera'),
('Mirada Putrescente','Objetivo visible, Tirada de Salvación de Constitucion 12 o 3d6 de daño necrótico'),
('Intuición Sobrecogedora','Objetivo visible, Tirada de Salvación enfrentada Carisma(enemigo) vs Sabiduria(propia), si gana aprenderá un dato del enemigo'),
('Guja','Ataque cuerpo a cuerpo, +7 a impactar, 2d10+4 de daño cortante'),
('Cambiar de Forma','Te trnasforma en un humanoide mediano o pequeño que hayas visto antes, o vuelves a tu forma original.'),
('Lucero del Alba','Ataque cuerpo a cuerpo, +4 a impactar, 2d8+2 de daño perforante'),
('Jabalina','Ataque cuerpo a cuerpo o a distancia, +4 a impactar, 2d6+2 de daño perforante'),
('Pico 1','Ataque cuerpo a cuerpo, +7 a impactar, 1d10+5 de daño perforante'),
('Caer','Ataque cuerpo a cuerpo, +3 a impactar, 1d6 de daño perforante por cada 10 pies de caida, tambien recibes la mitad del daño por la distacia recorrida'),
('Cascos','Ataque cuerpo a cuerpo, +6 a impactar, 2d8+4 de daño contundente y 2d6 de fuego'),
('Trote Etéreo','Puedes pasar al plano etéreo o viceversa, tu y hasta 3 criaturas acompañantes'),
('Invisibilidad Superior','Te vuelves invisible tu y tu equipo hasta realizar otra accion que no sea de movimiento o pierdas la concentración'),
('Cuernos 1','Ataque cuerpo a cuerpo, +7 a impactar, 1d12+4 de daño contundente'),
('Aliento de Fuego','Ataque a distancia en area, cono de 15 pies, Tirada de Salvación de Destreza 15 o 7d8 de daño de fuego, mitad si superan'),
('Pico 2','Ataque cuerpo a cuerpo, +13 a impactar, 2d8+9 de daño perforante'),
('Etérea','Entras al plano etereo o vuelves'),
('Provocar Pesadilla','Si te encuentras en el Etéreo, humanoide objetivo dormido, otorgas pesadillas y no se beneficiará del descanso u 1d10 de puntos de golpe máximos reducidos'),
('Ballesta Pesada','Ataque a distancia, +3 a impactar, 1d10+1 de daño perforante'),
('Hechizar','Humanoide objetivo, Tirada de Salvación de Sabiduria 15 o hechizado durante 1 dia obdeciendo cualquier orden del amo, siempre que no sea una orden suicida'),
('Beso Debilitador','Beso a criatura voluntaria o hechizada, Tirada de Salvación de Constitución 15 o 5d10+5 de daño psíquico, mitad si supera, los puntos de golpe máximos se ven reducis en la misma cantidad que el daño recibido'),
('Cuernos 2','Ataque cuerpo a cuerpo, +19 a impactar, 4d10+10 de daño perforante'),
('Cola 2','Ataque cuerpo a cuerpo, +19 a impactar, 4d6+10 de daño contundente, Tirada de Salvación de Fuerza 20 o derribado'),
('Presencia Aterradora','Cualquier cantidad de Criaturas a 120 pies, Tirada de Salvación de Sabiduria 17 o asustadas 1 min'),
('Cuerno','Ataque cuerpo a cuerpo, +7 a impactar, 1d8+4 de daño perforante'),
('Teletransporte','Hasta 3 crituras aliadas y a ti mismo, el destino debe ser una ubicación familiar del lanzador, 1 milla o menos'),
('Escudo Resplandeciente','Se crea un escudo brillante alrededor de ti mismo y otra criatura a 60 pies o menos, +2 al CA'),
('Ataque sin Armas','Ataque cuerpo a cuerpo, +9 a impactar, 1d8+4 de daño contundente'),
('Hijos de la Noche','Invocas 2d4 enjambres de murcielagos o ratas(interior) o 3d6 de lobos(exterior), solo durante la noche, te obedeceran durante 1h, tras esto huirán'),
('Mirada Escalofriante',' Criatura objetivo, Tirada de Salvación de Constitución 18 o 6d6 de daño de frío y quedará paralizado'),
('Aliento Gélido','Ataque a disntacia en area, cono 30 pies, Tirada de Salvación de Constitución 18 o 10d8 de daño de frío, mitad si superan'),
('Cimitarra','Ataque cuerpo a cuerpo, +3 a impactar, 1d6+1 de daño cortante'),
('Arco Corto','Ataque a distancia, +3 a impactar, 1d6+1 de daño perforante'),
('Tridente','Ataque cuerpo a cuerpo, +7a impactar, 1d6+4 de daño perforante'),
('Mini-Teletransporte','Te mueves a un espacio desocupado a un máximo de 60 pies y que puedas ver'),
('Golpe 1','Ataque cuerpo a cuerpo, +3 a impactar, 1d6+1 de daño contundente');